import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import { Toaster } from "@/components/ui/toaster";
import { Locale, i18n } from "@/i18n.config";
import "./globals.css";
import { cn } from "@/lib/utils"
import { Header } from "@/modules/Header/Header";
import { Container } from "@/containers/Container/Container";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18n.locales.map(locale => ({ lang: locale }))
}

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode,
  params: { lang: Locale }
}>) {
  return (
    <html lang={params.lang}>
      <body className={cn(
        "min-h-screen bg-background font-sans antialiased",
        fontSans.variable
      )}>
        <Header lang={params.lang} />
        
        <main>
          <Container>
            {children}
          </Container>
        </main>
        
        <Toaster />
      </body>
    </html>
  );
}
